sudo: required
services:
  - docker

before_install:
  - docker build -t andylyell/docker-react-2 -f Dockerfile.dev .

script:
  - docker run -e CI=true andylyell/docker-react-2 npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react-2"
  env: "Dockerreact2-env"
  bucket_name: "elasticbeanstalk-eu-west-2-791671475753"
  bucket_path: "docker-react-2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY